### ISSUE TITLE
mpl, эпизод 1 : размер маркера

### ISSUE THREAD

**Issue by avasyukov** [karimvafin/Python_3sem#2]
(Опять, конечно, почти офтоп. Но всё же.)

https://github.com/karimvafin/Python_3sem/blob/2bbdf3777e7c619e55d46d22b51b3d44b0416b35/lab_matplotlib/episode_1/episode_1.py#L18
А если первая точка будет в `(0; 0)`?

**Comment by karimvafin** [comment]
В принципе можно просто поставить какое-нибудь адекватное значение по умолчанию, типа r = 1. Если расстояния между точками меньше этого характерного размера, то подберется подходящее значение r, если же расстояния между точками больше, то мы получим просто обычное значение markersize.
