### ISSUE TITLE
lab_numpy, episode2 : скорость работы

### ISSUE THREAD

**Issue by avasyukov** [karimvafin/Python_3sem#6]
Это полностью правильная логика:
https://github.com/karimvafin/Python_3sem/blob/630272a5df18d3314b4f696c5bda8e4b6a6876fc/lab_numpy/episode2/episode2.py#L9-L11

Но от for-ов придётся всё же избавиться, по крайней мере для основной части массива.

Если развить магию слайсов, можно посмотреть на подход типа такого:
```
# это не логика из задачи, просто техническая демка, что можно делать со слайсами
z = np.arange(10)
z[:-1] = z[:-1] + z[1:]
print(z)
```

Ещё можно посмотреть на `cumsum` или `convolve`.

**Comment by karimvafin** [comment]
Исправил
